achievementData = {
	cardPath = "images/system/banner",
	iconPath = "images/system/icon",
	keyedAchievements = {"arcade1000", "arcade5000", "arcade10000", "arcade25000", "daily", "chill", "mission1", "mission50", "swaps50", "swaps100", "swaps250", "swaps500", "hexas50", "hexas100", "hexas250", "hexas500", "missioncommand"},
	achievements = {
		{
			id = "arcade1000",
			name = "HEXA Rookie",
			description = "Score 1,000 points in Arcade Mode",
			isSecret = false,
			progressMax = 1000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "arcade5000",
			name = "HEXA Novice",
			description = "Score 5,000 points in Arcade Mode",
			isSecret = false,
			progressMax = 5000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "arcade10000",
			name = "HEXA Expert",
			description = "Score 10,000 points in Arcade Mode",
			isSecret = false,
			progressMax = 10000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "arcade25000",
			name = "HEXA Master",
			description = "Score 25,000 points in Arcade Mode",
			isSecret = false,
			progressMax = 25000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "daily",
			name = "Checking In",
			description = "Play a Daily Run",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "chill",
			name = "Take a Chill Pill",
			description = "Play around in Chill Mode",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "mission1",
			name = "Modus Operandi",
			description = "Complete a Mission",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "mission50",
			name = "Mission Accomplished",
			description = "Complete all 50 Missions",
			progressMax = 50,
			progressIsPercentage = true,
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "swaps50",
			name = "Swap Meet",
			description = "Reach 50 Swaps (all-time)",
			isSecret = false,
			progressMax = 50,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "swaps100",
			name = "Swap Machina",
			description = "Reach 100 Swaps (all-time)",
			isSecret = false,
			progressMax = 100,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "swaps250",
			name = "The Swapper",
			description = "Reach 250 Swaps (all-time)",
			isSecret = false,
			progressMax = 250,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "swaps500",
			name = "Swapped Out",
			description = "Reach 500 Swaps (all-time)",
			isSecret = false,
			progressMax = 500,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "hexas50",
			name = "HEXA-spawn",
			description = "Reach 50 HEXAs (all-time)",
			isSecret = false,
			progressMax = 50,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "hexas100",
			name = "HEXA-gone",
			description = "Reach 100 HEXAs (all-time)",
			isSecret = false,
			progressMax = 100,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "hexas250",
			name = "HEXA-ton",
			description = "Reach 250 HEXAs (all-time)",
			isSecret = false,
			progressMax = 250,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "hexas500",
			name = "HEXA-god",
			description = "Reach 500 HEXAs (all-time)",
			isSecret = false,
			progressMax = 500,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "missioncommand",
			name = "Mission Command",
			description = "Create a custom mission",
			isSecret = true,
			scoreValue = 0,
		},
	}
}